import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import React from "react";
import { Navbar } from "@/components/navbar/Navbar";
import { Footer } from "@/components/footer/Footer";
import { Toaster } from "react-hot-toast";
import { getLoggedUserCartAction } from "@/services/actions/cart.action";
import { HttpResult } from "@/services/utils/http";
import { CartResponse } from "@/services/types/cart_interface";
import { GetWishlistResponse } from "@/services/types/wishlist_interface";
import { getWishlistAction } from "@/services/actions/wishlist.action";
import Providers from "./_providers/Providers";
import { getMyToken } from "@/services/utils/helpers/getMyToken";

const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Fresh Cart",
    template: "%s | Fresh Cart",
  },
  description: "Generated by Elsayed Mokdam",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Get user's cart
  const cartResponse: HttpResult<CartResponse | null> =
    await getLoggedUserCartAction();

  const userCart = cartResponse.ok ? cartResponse.data : null;

  // Get user's wishlist
  const wishlistResponse: HttpResult<GetWishlistResponse | null> =
    await getWishlistAction();

  const userWishlist = wishlistResponse.ok ? wishlistResponse.data : null;

  // Initial Redux state
  const preloadedState = {
    cart: {
      cartItems: userCart,
      numOfCartItems: userCart?.numOfCartItems ?? 0,
    },

    wishlist: {
      numOfWishlistItems: userWishlist?.count ?? 0,
    },
  };

  return (
    <html lang="en" className={`${exo.variable}`}>
      <body>
        {/* Client Boundary Pattern */}
        <Providers preloadedState={preloadedState}>
          <Navbar />
          {children}
          <Footer />
          <Toaster position="top-center" />
        </Providers>
      </body>
    </html>
  );
}
