import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import React from "react";
import { Navbar } from "@/components/navbar/Navbar";
import { Footer } from "@/components/footer/Footer";
import { Toaster } from "react-hot-toast";
import MySessionProvider from "./_providers/MySessionProvider";
import CartContextProvider from "./_providers/context/CartContextProvider";
import { getLoggedUserCartAction } from "@/services/actions/cart.action";
import { HttpResult } from "@/services/utils/http";
import { CartResponse } from "@/services/types/cart_interface";
import { getMyToken } from "@/services/utils/helpers/getMyToken";
import { GetWishlistResponse } from "@/services/types/wishlist_interface";
import { getWishlistAction } from "@/services/actions/wishlist.action";
import WishlistContextProvider from "./_providers/context/WishlistContextProvider";
const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next.js App",
    template: "%s | Next.js App",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartResponse: HttpResult<CartResponse | null> =
    await getLoggedUserCartAction();
  let userCart = null;
  if (cartResponse.ok) {
    userCart = cartResponse.data;
  }

  const wishlistResponse: HttpResult<GetWishlistResponse | null> =
    await getWishlistAction();
  let userWishlist = null;
  if (wishlistResponse.ok) {
    userWishlist = wishlistResponse.data;
  }

  const token = await getMyToken();
  return (
    <html lang="en" className={`${exo.variable}`}>
      <body>
        {/* Client Boundary Pattern */}
        <MySessionProvider>
          <WishlistContextProvider userWishlistLength={userWishlist?.count}>
            <CartContextProvider userCart={userCart}>
              <Navbar />
              {children}
              <Footer />
              <Toaster position="top-center" />
            </CartContextProvider>
          </WishlistContextProvider>
        </MySessionProvider>
      </body>
    </html>
  );
}
