import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import React from "react";
import { Navbar } from "@/components/navbar/Navbar";
import { Footer } from "@/components/footer/Footer";
import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "@/context/react-query-provider/ReactQueryProvider";
const exo = Exo({
  variable: "--font-exo",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next.js App",
    template: "%s | Next.js App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${exo.variable}`}>
      <body>
        <div className="mb-18">
          <Navbar />
        </div>
        {children}
        <Footer />
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
